site_name: OPAL - Oppositional Positions in Alabama
site_description: Web scraper used to search Alabama websites
site_author: Gabriel Cabán Cubero
site_url: 

repo_name: opal 
repo_url: 
edit_uri:

theme:
  name: material
  palette:
    #Light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    #Dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.copy

plugins:
  - search
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md 
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - CLI Usage: user-guide/cli-usage.md
    - Available Parsers: user-guide/parsers.md
    - Output Formats: user-guide/output-formats.md
  - Developer Guide:
    - Architecture: developer/architecture.md
    - BaseParser Guide: developer/BaseParser_web_scraping_guide.md
    - Creating New Parsers: developer/creating-parsers.md
    - ParserAppealsAL Documention: developer/ParserAppealsAL_documentation.md
  - About:
    - Contributing: about/contributing.md
    - License: about/license.md
