site_name: OPAL - Oppositional Positions in Alabama
site_description: Web scraper used to search Alabama websites
site_author: Gabriel Cabán Cubero
site_url: https://alabama-forward.github.io/opal/
use_directory_urls: true
docs_dir: docs
site_dir: site

repo_name: alabama-forward/opal 
repo_url: https://github.com/alabama-forward/opal
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    #Light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    #Dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alabama-forward/opal
  homepage: https://alabama-forward.github.io/opal/

plugins:
  - search
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md 
  - Getting Started:
    - Overview: getting-started/index.md
    - Prerequisites Checker: getting-started/prerequisites-checker.md
    - Complete Setup Guide: getting-started/complete-setup-guide.md
    - Environment-Specific Guides: getting-started/environment-guides.md
    - Configuration: getting-started/configuration.md
    - Quick Start Tutorial: getting-started/quickstart-tutorial.md
  - User Guide:
    - Overview: user-guide/index.md
    - CLI Reference: user-guide/cli-reference.md
    - Interactive Command Builder: user-guide/command-builder.md
    - Parsers:
      - Available Parsers: user-guide/parsers/index.md
      - Alabama Appeals Court: user-guide/parsers/ParserAppealsAL.md
      - 1819 News: user-guide/parsers/Parser1819.md
      - Daily News: user-guide/parsers/ParserDailyNews.md
    - Visual Flow Diagrams: user-guide/visual-flow-diagrams.md
    - Output Examples: user-guide/output-examples.md
    - Common Use Cases: user-guide/common-use-cases.md
    - Working with Output Data: user-guide/working-with-output-data.md
    - Understanding Errors: user-guide/understanding-errors.md
    - Configurable Court Extractor: user-guide/configurable_court_extractor.md
  - Developer Guide:
    - Overview: developer/index.md
    - Architecture: developer/architecture.md
    - Workflows: developer/workflows.md
    - Creating Custom Parsers: developer/creating-custom-parsers.md
    - Creating Court Parsers: developer/creating-court-parsers.md
    - Error Handling: developer/error_handling.md
    - Class Reference:
      - Overview: developer/class-reference/index.md
      - Base Parser: reference/base-parser.md
      - Parser Classes: reference/parser-classes-overview.md
      - Data Structures: reference/data_structures.md
      - Court Extractor Classes: reference/court-extractor-classes.md
      - Court URL Paginator: reference/court_url_paginator.md
    - Court Extractor Design: developer/configurable_court_extractor_design.md
    - User Agent Headers Guide: developer/user_agent_headers_guide.md
  - About:
    - Overview: about/index.md
    - Contributing: about/contributing.md
    - License: about/license.md
