site_name: OPAL - Oppositional Positions in Alabama
site_description: Web scraper used to search Alabama websites
site_author: Gabriel Cabán Cubero
site_url: 

repo_name: opal 
repo_url: 
edit_uri:

theme:
  name: material
  palette:
    #Light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    #Dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  - content.code.copy

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

plugins:
  - search
  - autorefs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md 
  - Getting Started:
    - Complete Setup Guide: getting-started/complete-setup-guide.md
    - Prerequisites Checker: getting-started/prerequisites-checker.md
    - Environment-Specific Guides: getting-started/environment-guides.md
    - Quick Start Tutorial: getting-started/quickstart-tutorial.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - CLI Usage: user-guide/cli-usage.md
    - Output Examples: user-guide/output-examples.md
    - Common Use Cases: user-guide/common-use-cases.md
    - Working with Output Data: user-guide/working-with-output-data.md
    - Understanding Errors: user-guide/understanding-errors.md
    - Command Line Tools: user-guide/command_line_tools.md
    - Configurable Court Extractor: user-guide/configurable_court_extractor.md
    - Available Parsers: user-guide/parsers.md
    - Output Formats: user-guide/output-formats.md
  - Class Reference:
    - Complete Reference Guide: reference_guide.md
    - Data Structures: reference/data_structures.md
    - ParserAppealsAL: reference/parser-appeals-al.md
    - Court URL Paginator: reference/court_url_paginator.md
    - Base Parser: reference/base-parser.md
    - Parser1819: reference/parser-1819.md
    - ParserDailyNews: reference/parser-daily-news.md
  - Developer Guide:
    - Architecture: developer/architecture.md
    - Workflows: developer/workflows.md
    - Error Handling: developer/error_handling.md
    - BaseParser Guide: developer/BaseParser_web_scraping_guide.md
    - Creating New Parsers: developer/creating-parsers.md
    - ParserAppealsAL Documentation: developer/ParserAppealsAL_documentation.md
    - Court Extractor Design: developer/configurable_court_extractor_design.md
    # - Court Scraper Analysis: developer/court_scraper_analysis.md
    # - Court Scraper Requirements: developer/court_scraper_requirements.md
    # - Alabama Appeals Instructions: developer/alabama_appeals_court_scraper_instructions.md
    - User Agent Headers Guide: developer/user_agent_headers_guide.md
  - About:
    - Contributing: about/contributing.md
    - License: about/license.md
