# This workflow builds Jekyll site and commits to main branch docs folder
name: Build Jekyll site

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '_config.yml'
      - 'index.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      
      - name: Build Jekyll site
        run: |
          gem install jekyll jekyll-theme-minimal
          jekyll build --source . --destination ./docs_output
      
      - name: Move built site to docs folder
        run: |
          rm -rf docs_site
          mv docs_output docs_site
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs_site
          git diff --staged --quiet || (git commit -m "Build Jekyll site" && git push)